# Use Node.js LTS
FROM node:20
# Set working directory
WORKDIR /usr/src/app
# Copy package.json and package-lock.json
COPY package*.json ./
# Install dependencies
RUN npm install
COPY . .
EXPOSE 4000
CMD ["npm", "run", "dev"]
